import config from '@ztd-me/eslint'

export default config({
  react: true,
  // Generated by Wrangler and checked for drift in CI.
  ignores: ['worker-configuration.d.ts'],
  typescript: { tsconfigRootDir: import.meta.dirname },
})
