import config from '@ztd-me/eslint'

export default config({
  react: { framework: 'vinext' },
  // Generated by Wrangler and checked for drift in CI.
  ignores: ['worker-configuration.d.ts'],
  typescript: { tsconfigRootDir: import.meta.dirname },
}, {
  name: 'website/worker-types',
  files: ['worker/**/*.ts', 'types/vinext-worker-entry.d.ts'],
  languageOptions: { parserOptions: { project: './tsconfig.worker.json' } },
}, {
  name: 'website/tooling-types',
  files: ['vite.config.ts'],
  languageOptions: { parserOptions: { project: './tsconfig.tooling.json' } },
})
