export const en = {
  "meta.description": "Projects, experiments, and notes by Zeithrold. Explore Shared Memory, Ledger, and a growing collection of useful tools.",
  "skip": "Skip to content",
  "navigation": "Main navigation",
  "home": "Zeithrold home",
  "work": "Projects",
  "spaces": "Spaces",
  "contact": "Contact",
  "language": "切换到中文",
  "dark": "Switch to dark theme",
  "light": "Switch to light theme",
  "eyebrow": "A PERSONAL INDEX",
  "hero.first": "Ideas into",
  "hero.second": "useful things.",
  "hero.description": "A home for my projects, small experiments, and things I write along the way.",
  "hero.explore": "Explore the projects",
  "hero.github": "Find me on GitHub",
  "sketch.label": "A FEW CONNECTED IDEAS",
  "sketch.memory": "Remember",
  "sketch.build": "Build",
  "sketch.explore": "Explore",
  "sketch.caption": "A little curiosity goes a long way.",
  "projects.heading": "Selected projects",
  "projects.note": "OPEN SOURCE / A WORK IN PROGRESS",
  "memory.category": "AI / KNOWLEDGE",
  "memory.title": "Shared Memory",
  "memory.description": "A private memory library shared across AI agents. One place to keep context, with HTTP and MCP interfaces.",
  "memory.visual": "One library. Many agents.",
  "memory.library": "Your memory library",
  "memory.context": "Context, connected",
  "ledger.category": "API / MOBILE",
  "ledger.title": "Ledger",
  "ledger.description": "An API and a Flutter client for exact, multi-currency personal accounting. Built as two parts of one system.",
  "ledger.visual": "Different currencies. Exact values.",
  "ledger.api": "Accounting API",
  "ledger.client": "Flutter client",
  "ledger.exact": "Precision by design",
  "ledger.precision": "Integer precision",
  "technologies": "Technologies",
  "tag.multicurrency": "Multi-currency",
  "source": "View source",
  "ledger.app": "Client source",
  "tools.title": "zeithrold/tools",
  "tools.stage": "Early development",
  "tools.description": "Cross-project tooling for inspecting checks, planning commands, and syncing Agent Skills.",
  "tools.note": "Inspect, plan, sync — more is taking shape.",
  "spaces.heading": "Elsewhere on ztd.me",
  "spaces.note": "TWO SPACES TO EXPLORE",
  "blog.title": "Notes & stories",
  "blog.description": "Writing, thinking, and a few things worth keeping.",
  "showcase.title": "Small experiments",
  "showcase.description": "A collection of interfaces and useful everyday tools. Each page, a little exploration.",
  "visit": "Visit",
  "contact.eyebrow": "KEEP IN TOUCH",
  "contact.heading": "Start with a hello.",
  "contact.description": "An idea, a question, or something you'd like to share? My inbox is open.",
  "footer.description": "Projects, notes, and a little curiosity.",
  "footer.back": "Back to top",
  "notfound.title": "A page still to be made.",
  "notfound.description": "There isn't a page at this address. The homepage is a good place to start.",
  "notfound.back": "Back to ztd.me",
} as const;

export type CopyKey = keyof typeof en;
export const zh: Record<CopyKey, string> = {
  "meta.description": "Zeithrold 的项目、实验与文字。探索 Shared Memory、Ledger，以及不断生长的小工具集合。",
  "skip": "跳转到正文",
  "navigation": "主导航",
  "home": "Zeithrold 主页",
  "work": "项目",
  "spaces": "空间",
  "contact": "联系",
  "language": "Switch to English",
  "dark": "切换到深色主题",
  "light": "切换到浅色主题",
  "eyebrow": "个人索引",
  "hero.first": "让想法，",
  "hero.second": "变得有用。",
  "hero.description": "这里收集我的项目、小小的实验，以及沿途写下的文字。",
  "hero.explore": "看看这些项目",
  "hero.github": "在 GitHub 找到我",
  "sketch.label": "一些相互连接的想法",
  "sketch.memory": "记住",
  "sketch.build": "构建",
  "sketch.explore": "探索",
  "sketch.caption": "一点好奇，能走很远。",
  "projects.heading": "项目选集",
  "projects.note": "开源 / 持续打磨",
  "memory.category": "AI / 知识",
  "memory.title": "Shared Memory",
  "memory.description": "供多个 AI Agent 共享的私有记忆库。将上下文放在一处，通过 HTTP 与 MCP 连接。",
  "memory.visual": "一个记忆库，连接多个 Agent。",
  "memory.library": "你的记忆库",
  "memory.context": "让上下文连接起来",
  "ledger.category": "API / 移动应用",
  "ledger.title": "Ledger",
  "ledger.description": "精确处理多币种个人记账的 API 与 Flutter 客户端。两个项目，组成同一个系统。",
  "ledger.visual": "不同币种，精确记录。",
  "ledger.api": "记账 API",
  "ledger.client": "Flutter 客户端",
  "ledger.exact": "从设计开始，保持精确",
  "ledger.precision": "整数精度",
  "technologies": "技术栈",
  "tag.multicurrency": "多币种",
  "source": "查看源码",
  "ledger.app": "客户端源码",
  "tools.title": "zeithrold/tools",
  "tools.stage": "早期开发",
  "tools.description": "跨项目工具，用于盘点检查入口、规划命令与同步 Agent Skills。",
  "tools.note": "Inspect、plan、sync —— 更多能力仍在成形。",
  "spaces.heading": "ztd.me 上的其他空间",
  "spaces.note": "两个值得逛逛的地方",
  "blog.title": "文字与记录",
  "blog.description": "写下思考，也留住一些值得记住的事情。",
  "showcase.title": "小小的实验",
  "showcase.description": "一些界面与日常小工具。每一页，都是一次小探索。",
  "visit": "访问",
  "contact.eyebrow": "保持联系",
  "contact.heading": "从一句你好开始。",
  "contact.description": "一个想法、一个问题，或是想分享的事情，都可以写信给我。",
  "footer.description": "项目、文字，和一点好奇。",
  "footer.back": "回到顶部",
  "notfound.title": "这一页，还未写下。",
  "notfound.description": "这个地址没有页面。不妨从主页开始看看。",
  "notfound.back": "回到 ztd.me",
};
